#!/bin/sh

uci set fstab.@global[0].anon_mount=1
uci commit fstab

uci -q delete network.globals.ula_prefix
uci -q delete network.wan6
uci -q delete network.lan.ip6assign
uci set network.wan.ifname='eth0'
uci set network.wan.proto='pppoe'
uci set network.wan.username='ctcc'
uci set network.wan.password='123456'
uci set network.wan.metric='10'
uci set network.wan2='interface'
uci set network.wan2.ifname='eth1'
uci set network.wan2.proto='pppoe'
uci set network.wan2.username='cmcc'
uci set network.wan2.password='123456'
uci set network.wan2.metric='20'
uci set network.lan.ifname='eth2 eth3'
uci set network.lan.delegate='0'
uci set network.WireGuard='interface'
uci set network.WireGuard.proto='wireguard'
uci set network.WireGuard.delegate='0'
uci set network.WireGuard.private_key='IK7iRJQuXXhmWImk/WajnoJH2GQXi7DuChrsZP0pNWA='
uci set network.WireGuard.listen_port='2000'
uci add_list network.WireGuard.addresses='192.168.100.1/24'
uci set network.wgclient='wireguard_WireGuard'
uci set network.wgclient.public_key='HxIQxXtLKyBBWT2gMzGIPZBLmPK7spiXZ58k/0upviQ='
uci set network.wgclient.preshared_key='RpONxptGpHcj/Plfunl4gREeJ6W50UX28G5XQHJz0BA='
uci set network.wgclient.route_allowed_ips='1'
uci add_list network.wgclient.allowed_ips='192.168.100.2/32'
uci commit network

uci add_list dhcp.@dnsmasq[0].notinterface='eth0'
uci add_list dhcp.@dnsmasq[0].notinterface='eth1'
uci commit dhcp

uci set firewall.@zone[1].network='wan wan2'
uci commit firewall

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='Compiled by DingYi'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt v18.06'" >> /etc/openwrt_release

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
