#!/bin/sh

uci set fstab.@global[0].anon_mount=1
uci commit fstab

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='Compiled by DingYi'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt v18.06'" >> /etc/openwrt_release

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
